Update ehtconsole

diff --git a/bin/ehtconsole b/bin/ehtconsole
--- a/bin/ehtconsole
+++ b/bin/ehtconsole
@@ -366,7 +366,7 @@ function banner
 		echo -e ""$YS" 1"$CE") Enable $WLANN${SPACESN}"$YS"d1"$CE") Disable $WLANN${SPACESN}   "$YS"start"$CE") Start monitor mode"
 		echo -e ""$YS" 2"$CE") Enable $WLANNM${SPACESM}"$YS"d2"$CE") Disable $WLANNM${SPACESM}    "$YS"stop"$CE") Stop monitor mode"
 	fi
-	echo -e ""$YS" 3"$CE") Change MAC        "$YS"d3"$CE") Restore original MAC "$YS"update"$CE") Check for updates"
+	echo -e ""$YS" 3"$CE") Change MAC        "$YS"d3"$CE") Restore MAC          "$YS"update"$CE") Check for updates"
 	if [[ -f /usr/bin/anonym8 ]]
 	then
 	echo -e ""$YS" 4"$CE") Enable anonym8    "$YS"d4"$CE") Disable anonym8      "$YS"errors"$CE") Fix some errors"
@@ -375,10 +375,10 @@ function banner
 	fi
 	if [[ -f /usr/bin/anonsurf ]]
 	then
-	echo -e ""$YS" 5"$CE") Enable anonsurf   "$YS"d5"$CE") Disable anonsurf         "$YS"ks"$CE") Keyboard shortucts"
+	echo -e ""$YS" 5"$CE") Enable anonsurf   "$YS"d5"$CE") Disable anonsurf         "$YS"ks"$CE") Keyboard shortcuts"
 	echo -e ""$YS" 6"$CE") Anonsurf's status "$YS"d6"$CE") Restart anonsurf          "$YS"s"$CE") Go to settings menu"
 	else
-	echo -e ""$RS" 5"$CE") Enable anonsurf   "$RS"d5"$CE") Disable anonsurf         "$YS"ks"$CE") Keyboard shortucts"
+	echo -e ""$RS" 5"$CE") Enable anonsurf   "$RS"d5"$CE") Disable anonsurf         "$YS"ks"$CE") Keyboard shortcuts"
 	echo -e ""$RS" 6"$CE") Anonsurf's status "$RS"d6"$CE") Restart anonsurf          "$YS"s"$CE") Go to settings menu"
 	fi
 	echo -e ""$YS" 7"$CE") View public IP"                                 
@@ -388,16 +388,16 @@ function banner
 	then
 		echo -e ""$YS"10"$CE") Handshake         "$YS"16"$CE") Ngrok port forward       "$QS"23"$CE") Arissploit"
 	else
-		echo -e ""$YS"10"$CE") Handshake         "$RS"16"$CE") "$RS"Ngrok"$CE" port forward       "$QS"23"$CE") Arissploit"      
+		echo -e ""$YS"10"$CE") Handshake         "$RS"16"$CE") Ngrok port forward       "$QS"23"$CE") Arissploit"      
 	fi
 	if [[ -f /usr/local/bin/howdoi ]]
 	then
 		echo -e ""$YS"11"$CE") Find WPS pin      "$YS"17"$CE") Ask (Howdoi tool)    "$YS"24"$CE") Reboot computer"
 	else
-		echo -e ""$YS"11"$CE") Find WPS pin      "$RS"17"$CE") Ask ("$RS"Howdoi"$CE" tool) "$YS"24"$CE") Reboot computer"
+		echo -e ""$YS"11"$CE") Find WPS pin      "$RS"17"$CE") Ask (Howdoi tool) "$YS"24"$CE") Reboot computer"
 	fi
 	echo -e ""$YS"12"$CE") WEP menu          "$YS"18"$CE") Auto-exploit browser     "$YS"25"$CE") Shutdown computer"
-	echo -e ""$YS"13"$CE") MITM              "$YS"19"$CE") Geolocate an IP          "$QE"26"$CE") Open ehtools shell"
+	echo -e ""$YS"13"$CE") MITM menu         "$YS"19"$CE") Geolocate an IP          "$QE"26"$CE") Open ehtools shell"
 	echo -e ""$YS"14"$CE") Metasploit        "$YS"20"$CE") Bruteforce login         "$YS"27"$CE") Update APT sources"
 	echo -e ""$YS" 0"$CE") Exit              "$YS"21"$CE") Sqlmap automated         "$YS"28"$CE") Change interfaces"
 	read -e -p $'(\033[4;93mehtools\033[0m\en)> ' YORNAA
@@ -409,13 +409,13 @@ function enable_wlan
 	O4=0
 	echo -e "Enabling $WLANN..."
 	rfkill unblock wifi &> /dev/null; rfkill unblock all &> /dev/null
-	ifconfig $WLANN up &>/dev/null && echo -e "["$YS"inf"$CE"] "$YS"Done"$CE"" && O4=1  || echo -e ""$RS"Error. I can't find your wireless adapter"$CE""
+	ifconfig $WLANN up &>/dev/null && echo -e "["$YS"inf"$CE"] "$YS"Done"$CE"" && O4=1  || echo -e ""$RS"ehtconsole returned an error (40) (wireless adapter is not found)"$CE""
 }
 function disable_wlan
 {
 	echo -e "Disabling $WLANN..."
 	rfkill unblock wifi &> /dev/null; rfkill unblock all &> /dev/null
-	ifconfig $WLANN down &>/dev/null && echo -e "["$YS"inf"$CE"] "$YS"Done"$CE"" && O4=1 || echo -e ""$RS"Error. I can't find your wireless adapter."$CE""
+	ifconfig $WLANN down &>/dev/null && echo -e "["$YS"inf"$CE"] "$YS"Done"$CE"" && O4=1 || echo -e ""$RS"ehtconsole returned an error (40) (wireless adapter is not found)"$CE""
 }
 function interface_selection
 {
