Add files via upload

diff --git a/bin/ehtmod b/bin/ehtmod
--- a/bin/ehtmod
+++ b/bin/ehtmod
@@ -35,7 +35,9 @@ N="\e[1;37m"
 
 if [[ $EUID -ne 0 ]]
 then
-   echo "["$RS"*"$CE"] "$RS"This script must be run as "$YS"root"$CE"" 1>&2
+   sleep 1
+   echo -e "["$RS"*"$CE"] "$RS"This script must be run as "$YS"root"$CE"" 1>&2
+   sleep 1
    exit
 fi
 
@@ -119,9 +121,9 @@ if [[ -d /etc/ehtools/modules ]]
 then
 if [[ ! -d /etc/ehtools/modules/snapshots ]]
 then
-sleep 3
+sleep 2
 echo -e "Error, snapshots directory is not found!"
-sleep 1
+sleep 2
 echo -e "Making /etc/ehtools/modules/snapshots..."
 mkdir /etc/ehtools/modules/snapshots
 sleep 0.5
@@ -223,15 +225,15 @@ echo -e "Finishing and exiting..."
 sleep 5
 exit
 else
-sleep 3
+sleep 2
 echo -e "Error, snapshot $2 is not found!"
-sleep 1
+sleep 2
 exit
 fi
 else
-sleep 3
-echo -e "Error, modules is not installed!"
-sleep 1
+sleep 2
+echo -e "Error, ehtools modules is not installed!"
+sleep 2
 exit
 fi
 
@@ -241,9 +243,9 @@ if [[ -d /etc/ehtools/modules ]]
 then
 if [[ ! -d /etc/ehtools/modules/snapshots ]]
 then
-sleep 3
+sleep 2
 echo -e "Error, snapshots directory is not found!"
-sleep 1
+sleep 2
 echo -e "Making /etc/ehtools/modules/snapshots..."
 mkdir /etc/ehtools/modules/snapshots
 sleep 0.5
@@ -299,15 +301,15 @@ echo -e "Finishing and exiting..."
 sleep 5
 exit
 else
-sleep 3
+sleep 2
 echo -e "Error, snapshot $2 is not found!"
-sleep 1
+sleep 2
 exit
 fi
 else
-sleep 3
-echo -e "Error, modules is not installed!"
-sleep 1
+sleep 2
+echo -e "Error, ehtools modules is not installed!"
+sleep 2
 exit
 fi
 
@@ -317,9 +319,9 @@ if [[ -d /etc/ehtools/modules ]]
 then
 if [[ ! -d /etc/ehtools/modules/snapshots ]]
 then
-sleep 3
+sleep 2
 echo -e "Error, snapshots directory is not found!"
-sleep 1
+sleep 2
 echo -e "Making /etc/ehtools/modules/snapshots..."
 mkdir /etc/ehtools/modules/snapshots
 sleep 0.5
@@ -328,9 +330,9 @@ sleep 1
 fi
 if [[ -d /etc/ehtools/modules/snapshots/$2 ]]
 then
-sleep 3
+sleep 2
 echo -e "Error, snapshot $2 is already taken!"
-sleep 1
+sleep 2
 exit
 else
 clear
@@ -390,9 +392,9 @@ sleep 5
 exit
 fi
 else
-sleep 3
-echo -e "Error, modules is not installed!"
-sleep 1
+sleep 2
+echo -e "Error, ehtools modules is not installed!"
+sleep 2
 exit
 fi
 
@@ -457,9 +459,9 @@ echo -e "Finishing and exiting..."
 sleep 5
 exit
 else
-sleep 3
+sleep 2
 echo -e "Error, ehtools modules is not installed!"
-sleep 1
+sleep 2
 exit
 fi
 
@@ -468,9 +470,9 @@ elif [[ $1 = "--install" || $1 = "-i" ]]
 then
 if [[ -d /etc/ehtools/modules ]]
 then
-sleep 3
+sleep 2
 echo -e "Error, ehtools modules is already installed!"
-sleep 1
+sleep 2
 exit
 fi
 clear
diff --git a/etc/lite/bin/ehtapp b/etc/lite/bin/ehtapp
--- a/etc/lite/bin/ehtapp
+++ b/etc/lite/bin/ehtapp
@@ -35,7 +35,9 @@ N="\e[1;37m"
 
 if [[ $EUID -ne 0 ]]
 then
-   echo "["$RS"*"$CE"] "$RS"This script must be run as "$YS"root"$CE"" 1>&2
+   sleep 1
+   echo -e "["$RS"*"$CE"] "$RS"This script must be run as "$YS"root"$CE"" 1>&2
+   sleep 1
    exit
 fi
 
@@ -44,11 +46,11 @@ then
 echo -e "Usage: ehtapp [OPTION...]"
 echo -e "Copyright (C) 2019, Entynetproject. All Rights Reserved."
 echo -e
-echo -e "   -c  --create            Create ehtools shortcut application."
+echo -e "   -c  --create            Create ehtools application."
 echo -e "                             (create shortcut application)"
-echo -e "   -d  --desktop <option>  Create/remove ehtools desktop shortcut application."
+echo -e "   -d  --desktop <option>  Create/remove ehtools desktop application."
 echo -e "                             (create/remove desktop shortcut application)" 
-echo -e "   -r  --remove            Remove ehtools shortcut application."
+echo -e "   -r  --remove            Remove ehtools application."
 echo -e "                             (remove shortcut application)"
 echo -e "   -h  --help              Give this help list."
 exit
@@ -58,14 +60,14 @@ then
 if [[ -f /usr/share/applications/ehtools.desktop ]]
 then
 sleep 2
-echo -e "Error, ehtools shortcut application is already created!"
+echo -e "Error, ehtools application is already created!"
 sleep 2
 exit
 else
 sleep 2
 cp /root/ehtools/app/ehtools.desktop /usr/share/applications
 chmod +x /usr/share/applications/ehtools.desktop
-echo -e "Success, ehtools shortcut application created!"
+echo -e "Success, ehtools application created!"
 sleep 2
 exit
 fi
@@ -78,14 +80,14 @@ then
 if [[ -f /root/Desktop/ehtools.desktop ]]
 then
 sleep 2
-echo -e "Error, ehtools desktop shortcut application is already created!"
+echo -e "Error, ehtools desktop application is already created!"
 sleep 2
 exit
 else
 sleep 2
 cp /root/ehtools/app/ehtools.desktop /root/Desktop
 chmod +x /root/Desktop/ehtools.desktop
-echo -e "Success, ehtools desktop shortcut application created!"
+echo -e "Success, ehtools desktop application created!"
 sleep 2
 exit
 fi
@@ -96,11 +98,11 @@ if [[ -f /root/Desktop/ehtools.desktop ]]
 then
 sleep 2
 rm /root/Desktop/ehtools.desktop
-echo -e "Success, ehtools desktop shortcut application removed!"
+echo -e "Success, ehtools desktop application removed!"
 sleep 2
 else
 sleep 2
-echo -e "Error, ehtools desktop shortcut application is not created!"
+echo -e "Error, ehtools desktop application is not created!"
 sleep 2
 exit
 fi
@@ -113,11 +115,11 @@ if [[ -f /usr/share/applications/ehtools.desktop ]]
 then
 sleep 2
 rm /usr/share/applications/ehtools.desktop
-echo -e "Success, ehtools shortcut application removed!"
+echo -e "Success, ehtools application removed!"
 sleep 2
 else
 sleep 2
-echo -e "Error, ehtools shortcut application is not created!"
+echo -e "Error, ehtools application is not created!"
 sleep 2
 exit
 fi
@@ -126,11 +128,11 @@ fi
 echo -e "Usage: ehtapp [OPTION...]"
 echo -e "Copyright (C) 2019, Entynetproject. All Rights Reserved."
 echo -e
-echo -e "   -c  --create            Create ehtools shortcut application."
+echo -e "   -c  --create            Create ehtools application."
 echo -e "                             (create shortcut application)"
-echo -e "   -d  --desktop <option>  Create/remove ehtools desktop shortcut application."
+echo -e "   -d  --desktop <option>  Create/remove ehtools desktop application."
 echo -e "                             (create/remove desktop shortcut application)" 
-echo -e "   -r  --remove            Remove ehtools shortcut application."
+echo -e "   -r  --remove            Remove ehtools application."
 echo -e "                             (remove shortcut application)"
 echo -e "   -h  --help              Give this help list."
 exit
diff --git a/etc/lite/bin/ehtmod b/etc/lite/bin/ehtmod
--- a/etc/lite/bin/ehtmod
+++ b/etc/lite/bin/ehtmod
@@ -35,7 +35,9 @@ N="\e[1;37m"
 
 if [[ $EUID -ne 0 ]]
 then
-   echo "["$RS"*"$CE"] "$RS"This script must be run as "$YS"root"$CE"" 1>&2
+   sleep 1
+   echo -e "["$RS"*"$CE"] "$RS"This script must be run as "$YS"root"$CE"" 1>&2
+   sleep 1
    exit
 fi
 
@@ -63,9 +65,9 @@ if [[ -d /etc/ehtools/modules ]]
 then
 if [[ ! -d /etc/ehtools/modules/snapshots ]]
 then
-sleep 3
+sleep 2
 echo -e "Error, snapshots directory is not found!"
-sleep 1
+sleep 2
 echo -e "Making /etc/ehtools/modules/snapshots..."
 mkdir /etc/ehtools/modules/snapshots
 sleep 0.5
@@ -167,15 +169,15 @@ echo -e "Finishing and exiting..."
 sleep 5
 exit
 else
-sleep 3
+sleep 2
 echo -e "Error, snapshot $2 is not found!"
-sleep 1
+sleep 2
 exit
 fi
 else
-sleep 3
-echo -e "Error, modules is not installed!"
-sleep 1
+sleep 2
+echo -e "Error, ehtools modules is not installed!"
+sleep 2
 exit
 fi
 
@@ -185,9 +187,9 @@ if [[ -d /etc/ehtools/modules ]]
 then
 if [[ ! -d /etc/ehtools/modules/snapshots ]]
 then
-sleep 3
+sleep 2
 echo -e "Error, snapshots directory is not found!"
-sleep 1
+sleep 2
 echo -e "Making /etc/ehtools/modules/snapshots..."
 mkdir /etc/ehtools/modules/snapshots
 sleep 0.5
@@ -243,15 +245,15 @@ echo -e "Finishing and exiting..."
 sleep 5
 exit
 else
-sleep 3
+sleep 2
 echo -e "Error, snapshot $2 is not found!"
-sleep 1
+sleep 2
 exit
 fi
 else
-sleep 3
-echo -e "Error, modules is not installed!"
-sleep 1
+sleep 2
+echo -e "Error, ehtools modules is not installed!"
+sleep 2
 exit
 fi
 
@@ -261,9 +263,9 @@ if [[ -d /etc/ehtools/modules ]]
 then
 if [[ ! -d /etc/ehtools/modules/snapshots ]]
 then
-sleep 3
+sleep 2
 echo -e "Error, snapshots directory is not found!"
-sleep 1
+sleep 2
 echo -e "Making /etc/ehtools/modules/snapshots..."
 mkdir /etc/ehtools/modules/snapshots
 sleep 0.5
@@ -272,9 +274,9 @@ sleep 1
 fi
 if [[ -d /etc/ehtools/modules/snapshots/$2 ]]
 then
-sleep 3
+sleep 2
 echo -e "Error, snapshot $2 is already taken!"
-sleep 1
+sleep 2
 exit
 else
 clear
@@ -334,9 +336,9 @@ sleep 5
 exit
 fi
 else
-sleep 3
-echo -e "Error, modules is not installed!"
-sleep 1
+sleep 2
+echo -e "Error, ehtools modules is not installed!"
+sleep 2
 exit
 fi
 
@@ -401,9 +403,9 @@ echo -e "Finishing and exiting..."
 sleep 5
 exit
 else
-sleep 3
+sleep 2
 echo -e "Error, ehtools modules is not installed!"
-sleep 1
+sleep 2
 exit
 fi
 
@@ -412,9 +414,9 @@ elif [[ $1 = "--install" || $1 = "-i" ]]
 then
 if [[ -d /etc/ehtools/modules ]]
 then
-sleep 3
+sleep 2
 echo -e "Error, ehtools modules is already installed!"
-sleep 1
+sleep 2
 exit
 fi
 clear
